In [1]:
#PIP
#How to install and where to install
# Numpy and camelcase

In [2]:
import numpy as np

In [7]:
arr_0D = np.array(42)

print(arr_0D)

42


In [8]:
arr_1D = np.array([1, 2, 3, 4, 5])

print(arr_1D)

[1 2 3 4 5]


In [9]:
# 2D Array - Nested array -- An array which has 1-D array is a element of the Array
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2D)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3D
arr_3D = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_3D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
#Number of dimensions

print(arr_0D.ndim)
print(arr_1D.ndim)
print(arr_2D.ndim)
print(arr_3D.ndim)

0
1
2
3


In [16]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [34]:
# 4D & 5D -- homework
d = np.array([[[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]]])
e = np.array([[[[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [7, 8, 9]]]]])
print(d.ndim)
print(e.ndim)




4
5


In [21]:


arr_15 = np.array([1, 2, 3, 4], ndmin=6)

print(arr_15)
print('number of dimensions :', arr_15.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6
